package setCubeBuilder;

import java.awt.CardLayout;
import java.awt.event.WindowEvent;

import javax.swing.*;
import org.apache.commons.lang3.*;

public class SetCubeBuilderUI extends javax.swing.JFrame {

    /*
     * Creates new form ContactEditorUI
     */
    public SetCubeBuilderUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

                container = new javax.swing.JPanel();
                prompts = new javax.swing.JPanel();
                setCode = new javax.swing.JLabel();
                numMythics = new javax.swing.JLabel();
                numRares = new javax.swing.JLabel();
                numUncommons = new javax.swing.JLabel();
                numCommons = new javax.swing.JLabel();
                filename = new javax.swing.JLabel();
                setCodeField = new javax.swing.JTextField();
                numMythicsField = new javax.swing.JTextField();
                numRaresField = new javax.swing.JTextField();
                numUncommonsField = new javax.swing.JTextField();
                numCommonsField = new javax.swing.JTextField();
                filenameField = new javax.swing.JTextField();
                submit = new javax.swing.JButton();
                finished = new javax.swing.JPanel();
                close = new javax.swing.JButton();
                closeText = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Set Cube Builder");

                container.setPreferredSize(new java.awt.Dimension(600, 250));
                container.setLayout(new java.awt.CardLayout());

                prompts.setPreferredSize(new java.awt.Dimension(600, 250));
                prompts.setRequestFocusEnabled(false);

                setCode.setLabelFor(setCodeField);
                setCode.setText(" Enter the three letter set code:");
                setCode.setMaximumSize(new java.awt.Dimension(35, 30));
                setCode.setMinimumSize(new java.awt.Dimension(35, 20));
                setCode.setPreferredSize(new java.awt.Dimension(70, 24));

                numMythics.setLabelFor(setCodeField);
                numMythics.setText(" Enter how many copies you want of each mythic:");
                numMythics.setMaximumSize(new java.awt.Dimension(35, 30));
                numMythics.setMinimumSize(new java.awt.Dimension(35, 20));
                numMythics.setPreferredSize(new java.awt.Dimension(70, 24));

                numRares.setLabelFor(setCodeField);
                numRares.setText(" Enter how many copies you want of each rare:");
                numRares.setMaximumSize(new java.awt.Dimension(35, 30));
                numRares.setMinimumSize(new java.awt.Dimension(35, 20));
                numRares.setPreferredSize(new java.awt.Dimension(70, 24));

                numUncommons.setLabelFor(setCodeField);
                numUncommons.setText(" Enter how many copies you want of each uncommon:");
                numUncommons.setMaximumSize(new java.awt.Dimension(35, 30));
                numUncommons.setMinimumSize(new java.awt.Dimension(35, 20));
                numUncommons.setPreferredSize(new java.awt.Dimension(70, 24));

                numCommons.setLabelFor(setCodeField);
                numCommons.setText(" Enter how many copies you want of each common:");
                numCommons.setMaximumSize(new java.awt.Dimension(35, 30));
                numCommons.setMinimumSize(new java.awt.Dimension(35, 20));
                numCommons.setPreferredSize(new java.awt.Dimension(70, 24));

                filename.setLabelFor(setCodeField);
                filename.setText(" Enter the filename you want the list outputted as:");
                filename.setMaximumSize(new java.awt.Dimension(35, 30));
                filename.setMinimumSize(new java.awt.Dimension(35, 30));
                filename.setPreferredSize(new java.awt.Dimension(70, 24));

                setCodeField.setText("Ex: DOM");
                setCodeField.setPreferredSize(new java.awt.Dimension(70, 24));

                numMythicsField.setText("0");
                numMythicsField.setPreferredSize(new java.awt.Dimension(70, 24));
                numMythicsField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                numMythicsFieldActionPerformed(evt);
                        }
                });

                numRaresField.setText("0");
                numRaresField.setPreferredSize(new java.awt.Dimension(70, 24));
                numRaresField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                numRaresFieldActionPerformed(evt);
                        }
                });

                numUncommonsField.setText("0");
                numUncommonsField.setPreferredSize(new java.awt.Dimension(70, 24));
                numUncommonsField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                numUncommonsFieldActionPerformed(evt);
                        }
                });

                numCommonsField.setText("0");
                numCommonsField.setPreferredSize(new java.awt.Dimension(70, 24));
                numCommonsField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                numCommonsFieldActionPerformed(evt);
                        }
                });

                filenameField.setText("cards.txt");
                filenameField.setPreferredSize(new java.awt.Dimension(70, 24));
                filenameField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                filenameFieldActionPerformed(evt);
                        }
                });

                submit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
                submit.setText("Submit");
                submit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                submitActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout promptsLayout = new javax.swing.GroupLayout(prompts);
                prompts.setLayout(promptsLayout);
                promptsLayout.setHorizontalGroup(
                        promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(promptsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptsLayout.createSequentialGroup()
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(filename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numCommons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numUncommons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numRares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numMythics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(setCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(setCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                        .addComponent(numMythicsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numRaresField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numUncommonsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numCommonsField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(filenameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );
                promptsLayout.setVerticalGroup(
                        promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promptsLayout.createSequentialGroup()
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(setCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(numMythicsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numMythics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numRaresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numRares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numUncommons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numUncommonsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(numCommons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numCommonsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(promptsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                container.add(prompts, "card3");

                finished.setPreferredSize(new java.awt.Dimension(600, 250));

                close.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                close.setText("Close");
                close.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                closeActionPerformed(evt);
                        }
                });

                closeText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                closeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                closeText.setText("The card list has been saved as:");

                javax.swing.GroupLayout finishedLayout = new javax.swing.GroupLayout(finished);
                finished.setLayout(finishedLayout);
                finishedLayout.setHorizontalGroup(
                        finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(finishedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(finishedLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(closeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                finishedLayout.setVerticalGroup(
                        finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishedLayout.createSequentialGroup()
                                .addContainerGap(118, Short.MAX_VALUE)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(finishedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(finishedLayout.createSequentialGroup()
                                        .addComponent(closeText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 137, Short.MAX_VALUE)))
                );

                container.add(finished, "card2");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>                        

    private void numMythicsFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void numRaresFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void numUncommonsFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void numCommonsFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void filenameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    //take all the data from the form and use it to call SetCubeBuilder
    //in order to generate the list of cards
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	
    	
    	if (validateInput()) 
    	{
    		
			
			//fetch the filename and setcode from the text fields
			String filename = filenameField.getText();
			String set = setCodeField.getText();
			
			//fetch the number of the different rarities from their fields and 
			//parse them to ints for the setcubebuilder class
			String temp = numMythicsField.getText();
			int mythics = Integer.parseInt(temp);
			temp = numRaresField.getText();
			int rares = Integer.parseInt(temp);
			temp = numUncommonsField.getText();
			int uncommons = Integer.parseInt(temp);
			temp = numCommonsField.getText();
			int commons = Integer.parseInt(temp);
			
			submit.setText("Running");
			
			SetCubeBuilder setList = new SetCubeBuilder(filename,set,mythics,rares,uncommons,commons); 
			
            CardLayout cardLayout = (CardLayout)(container.getLayout());
            closeText.setText(closeText.getText() + " " + filenameField.getText());
            cardLayout.next(container);
			
    	}
    	else
    	{
    		submit.setText("Fix Errors and Try Again");
    	}
    	
    }                                      
    

	private void closeActionPerformed(java.awt.event.ActionEvent evt) {                                      
			// TODO add your handling code here:
		//container.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
		dispose();

	}                                     

    //input validation of all of the different fields
    private Boolean validateInput()
    {
    	Boolean check = false;
    	int countCorrect = 0;
    	
    	//validate the set code
    	if (setCodeField.getText().length() != 3)
    		setCodeField.setText("Try again (like DOM)");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//validate the number of mythics
    	if (!StringUtils.isNumeric(numMythicsField.getText()))
    		numMythicsField.setText("Please enter a number like 1");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//validate the number of rares
    	if (!StringUtils.isNumeric(numRaresField.getText()))
    		numRaresField.setText("Please enter a number like 1");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//validate the number of uncommons
    	if (!StringUtils.isNumeric(numUncommonsField.getText()))
    		numUncommonsField.setText("Please enter a number like 1");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//validate the number of commons
    	if (!StringUtils.isNumeric(numCommonsField.getText()))
    		numCommonsField.setText("Please enter a number like 1");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//validate the the filename existss
    	if (StringUtils.isEmpty(filenameField.getText()))
    		filenameField.setText("Please enter a filename");
    	else
    		countCorrect = countCorrect + 1;
    	
    	//if every check passed the count should equal 6
    	if (countCorrect == 6)
    		check = true;
    	
    	return check;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetCubeBuilderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetCubeBuilderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetCubeBuilderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetCubeBuilderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetCubeBuilderUI().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify                     
        private javax.swing.JButton close;
        private javax.swing.JLabel closeText;
        private javax.swing.JPanel container;
        private javax.swing.JLabel filename;
        private javax.swing.JTextField filenameField;
        private javax.swing.JPanel finished;
        private javax.swing.JLabel numCommons;
        private javax.swing.JTextField numCommonsField;
        private javax.swing.JLabel numMythics;
        private javax.swing.JTextField numMythicsField;
        private javax.swing.JLabel numRares;
        private javax.swing.JTextField numRaresField;
        private javax.swing.JLabel numUncommons;
        private javax.swing.JTextField numUncommonsField;
        private javax.swing.JPanel prompts;
        private javax.swing.JLabel setCode;
        private javax.swing.JTextField setCodeField;
        private javax.swing.JButton submit;
        // End of variables declaration                   
}